### ISSUE TITLE
Full dependency list

### ISSUE THREAD

**Issue by jjaquinta** [Ullink/simple-slack-api#1]
I'm trying to use this in a vanilla Eclipse Java project. Since I might want to use this in the company I work for, I want to keep a strict understanding of what other dependencies this uses. (They are allergic to certain Open Source licenses, but fine with others.) So rather than let gradle spider out and download the world, I'm trying to assemble the jar files by hand. So far I have:
javax.websocket-api-1.1.jar
json-simple-1.1.1.jar
slf4j-api-1.7.10.jar
slf4j-simple-1.7.10.jar
tyrus-client-1.9.jar
tyrus-core-1.9.jar
It compiles file. When I call session.connect() it connects, lists the channels, notifies of found users, bots and channels, then exceptions:

java.lang.RuntimeException: javax.websocket.DeploymentException: org.glassfish.tyrus.container.grizzly.client.GrizzlyClientContainer

	at org.glassfish.tyrus.client.ClientManager.<init>(ClientManager.java:269)
	at org.glassfish.tyrus.client.ClientManager.createClient(ClientManager.java:237)
	at org.glassfish.tyrus.client.ClientManager.createClient(ClientManager.java:216)
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connect(SlackWebSocketSessionImpl.java:125)
	at com.ibm.ba.cloud.slack.test.ConnectTest.main(ConnectTest.java:13)
Caused by: javax.websocket.DeploymentException: org.glassfish.tyrus.container.grizzly.client.GrizzlyClientContainer

	at org.glassfish.tyrus.core.ErrorCollector.composeComprehensiveException(ErrorCollector.java:83)
	... 5 more

I'm guessing this is a problem in my environment rather than in the code. Did I miss a tyrus jar?
Thanks,
Jo

**Comment by bcorne** [comment]
Hi,

Sorry for the delay, normally you only need the following dependencies : 

 org.glassfish.tyrus.bundles:tyrus-standalone-client:1.8.3 
 com.googlecode.json-simple:json-simple:1.1
 org.slf4j:slf4j-simple:1.7.7
 org.slf4j:slf4j-api:1.7.7

Please keep me informed if you still have the issue, I leave the issue open in case of.

Best regards,

Benoit
