### ISSUE TITLE
SlackWebSocketSessionImpl throws NPE on HTTP 429 Too Many Requests Response

### ISSUE THREAD

**Issue by tekknick** [Ullink/simple-slack-api#108]
If Slack throttles API requests by returning `HTTP 429 Too Many Requests`, then `SlackWebSocketSessionImpl.connectImpl()` throws a `NullPointerException` on line 278 (v0.5.1).

The response body includes the message `"You are sending too many requests. Please relax."` which causes `sessionParser.getTeam();` to return `null` and the `team.getId()` log statement that immediately follows throws the NPE.

```
[error] Caused by: java.lang.NullPointerException
[error]     at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connectImpl(SlackWebSocketSessionImpl.java:278)
[error]     at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connect(SlackWebSocketSessionImpl.java:230)
```

**Comment by gluck** [comment]
What behavior would you expect in this case ? an exception still (a better one :smile: ) or something else ? (retry, sleep & retry, or measure the rate and pause requests to adapt...)

**Comment by tekknick** [comment]
I think I'd keep the API minimal and defer the throttling strategy to clients. Maybe throw `org.apache.http.client.HttpResponseException` and include the status code. It's simple and doesn't change the `throws` signature of the method.

The [Slack Rate Limits](https://api.slack.com/docs/rate-limits) documentation says they include a `Retry-After` header that would be a nice to have. To support that though would probably require a subclass of `HttpResponseException`, perhaps `TooManyRequestsException`, that could include an `int getRetryAfterSecs()` method as well.

**Comment by msagi** [comment]
Added pull request with Slack API rate limit support https://github.com/Ullink/simple-slack-api/pull/229
