### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/websocket/MessageHandler$Whole

### ISSUE THREAD

**Issue by stargatesix** [Ullink/simple-slack-api#111]
Hi there,

I am getting the following stack trace when trying to use the session.connect() method.

`java.lang.NoClassDefFoundError: javax/websocket/MessageHandler$Whole
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:235)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:37)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.ullink.slack.simpleslackapi.impl.SlackSessionFactory.createWebSocketSlackSession(SlackSessionFactory.java:10)
        at com.test.chat.ChatPlugin.onEnable(ChatPlugin.java:34)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:386)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:264)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:246)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:387)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:374)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:208)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.ClassNotFoundException: javax.websocket.MessageHandler$Whole
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 27 more
`

Sorry if this is a duplicate issue.
Best regards,
Brandon.

**Comment by stargatesix** [comment]
Edited: I seemed to fix this error, but now I have a new one:

http://i.imgur.com/U92vDKB.png

(Sorry for using an external site, it was just a lot easier)

Hope someone can help and thanks for your time!

**Comment by VoidWhisperer** [comment]
How did you fix the first error you had here?

**Comment by bcorne** [comment]
If it's for the first strack trace, some libraries were missing in the classpath (tyrus)

**Comment by stargatesix** [comment]
Yes they were, for all those who use maven and want the repos I'll copy & paste my POM. :)

`
        
        <dependency>
            <groupId>org.glassfish.tyrus.bundles</groupId>
            <artifactId>tyrus-standalone-client</artifactId>
            <version>1.8.3</version>
        </dependency>
        
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
        </dependency>
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.6.1</version>
        </dependency>
        
        
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.2</version>
        </dependency>
        
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>18.0</version>
        </dependency>
        
        <dependency>
            <groupId>commons-logging</groupId>
            <artifactId>commons-logging</artifactId>
            <version>1.1.1</version>
        </dependency>`

@VoidWhisperer

**Comment by adriens** [comment]
Hi there, i run the client from a maven jar project and i'm experiencing the same issue.
Hence, is tyrus the lightest jar to add ?...as i don't want my jar to be to fat ?

**Comment by jvz** [comment]
I'm still getting the same exact error using SBT. My dependencies:

```
lazy val akkaVersion = "2.5.3"

libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-actor" % akkaVersion,
  "com.ullink.slack" % "simpleslackapi" % "1.0.0",
  "org.glassfish.tyrus.bundles" % "tyrus-standalone-client" % "1.13.1"
)
```

When I try to run the application via `sbt run`, I get `java.lang.NoClassDefFoundError: javax/websocket/MessageHandler$Whole`.

**Comment by adonix** [comment]
I'm seeing the same error here too.

**Comment by sakebook** [comment]
I'm also resolved in Gradle too.

```
dependencies {
    compile "com.ullink.slack:simpleslackapi:1.0.0"
    compile "org.glassfish.tyrus.bundles:tyrus-standalone-client:1.8.3"
}
```
