### ISSUE TITLE
Can't use bot without proxy

### ISSUE THREAD

**Issue by KingFaris10** [Ullink/simple-slack-api#116]
It won't let me connect without using a proxy.
This is how I create a session:
SlackSessionFactory.createWebSocketSlackSession(BOT_AUTH_TOKEN, 30, TimeUnit.SECONDS);

Error:
```
java.lang.IllegalArgumentException: Host name may not be null
	at org.apache.http.util.Args.containsNoBlanks(Args.java:81)
	at org.apache.http.HttpHost.<init>(HttpHost.java:80)
	at org.apache.http.HttpHost.<init>(HttpHost.java:99)
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.<init>(SlackWebSocketSessionImpl.java:224)
	at com.ullink.slack.simpleslackapi.impl.SlackSessionFactory.createWebSocketSlackSession(SlackSessionFactory.java:25)
	at com.faris.bot.SlackBot.main(SlackBot.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by KingFaris10** [comment]
Works when I only do:
SlackSessionFactory.createWebSocketSlackSession(BOT_AUTH_TOKEN);

I thought the time inputted was connection timeout time, not proxy timeout time. If it's proxy timeout time, I'll close this.

**Comment by bcorne** [comment]
It's the heartbeat setting to detect the Slack websocket disconnection (set to 30s by default). Anyway these methods are meant to be deprecated in favor of a builder mechanism (you can have a look at it on the GSON_migration branch)

**Comment by KingFaris10** [comment]
Oh right, it's fine I wanted it 30seconds anyway, didn't know it was default.
