### ISSUE TITLE
NPE when logging in SlackWebSocketSessionImpl

### ISSUE THREAD

**Issue by SenhorCastor** [Ullink/simple-slack-api#134]
Hi, just updated to 0.6.0 and I am seeing:

```
Exception in thread "Thread-1" java.lang.NullPointerException
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connectImpl(SlackWebSocketSessionImpl.java:279)
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.access$700(SlackWebSocketSessionImpl.java:42)
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl$2.run(SlackWebSocketSessionImpl.java:376)
```

Its a logger, not a big deal

``
     team = sessionParser.getTeam();
        LOGGER.info("Team " + team.getId() + " : " + team.getName());
        LOGGER.info("Self " + sessionPersona.getId() + " : " + sessionPersona.getUserName());
  ```

**Comment by david-romero** [comment]
The NPE is due to many connections to the Slack server in a very short time. 
The 'toParse' attribute of the 'SlackJSONSessionStatusParser' class contains the text 'Too many request. relax'

Regards

**Comment by bcorne** [comment]
ok, I need to have the parser to be more robust
