### ISSUE TITLE
java.lang.IllegalStateException: unknown user id: null (Multiple responses come from the bot after this exception)

### ISSUE THREAD

**Issue by sethu424** [Ullink/simple-slack-api#169]
920022 [Grizzly(1)] ERROR com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - Endpoint#onError called
java.lang.IllegalStateException: unknown user id: null
        at com.ullink.slack.simpleslackapi.impl.SlackJSONMessageParser.parseMessagePublished(SlackJSONMessageParser.java:236)
        at com.ullink.slack.simpleslackapi.impl.SlackJSONMessageParser.extractMessageEvent(SlackJSONMessageParser.java:177)
        at com.ullink.slack.simpleslackapi.impl.SlackJSONMessageParser.decode(SlackJSONMessageParser.java:66)
        at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.onMessage(SlackWebSocketSessionImpl.java:883)
        at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.onMessage(SlackWebSocketSessionImpl.java:41)
        at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:576)
        at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:879)
        at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:216)
        at org.glassfish.tyrus.core.frame.TextFrame.respond(TextFrame.java:139)
        at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:807)
        at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:747)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:476)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:114)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:272)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
        at java.lang.Thread.run(Thread.java:745)

**Comment by Omertron** [comment]
I also get this error with the latest build

**Comment by Omertron** [comment]
Ok, a little investigation and it seems to happen when the bot gets a response to a thread.

It might be because there are more than one "user" fields in the message?

**Comment by alextjp** [comment]
happens when commenting on an uploaded picture
