### ISSUE TITLE
Constantly Disconnected

### ISSUE THREAD

**Issue by david-hosier** [Ullink/simple-slack-api#175]
Hi, I'm using the 0.6.0 release to get started on a new bot, and I'm having an issue with a constant losing of the connection. The log shows that I'm connecting, then it shows an error, and then it shows that it reconnects 30 seconds later...rinse and repeat.

I'm using the following simple code to connect:
```
final SlackSession session = SlackSessionFactory.createWebSocketSlackSession("<elided>");
session.connect();
session.setPresence(SlackPresence.AUTO);
```

And below is the log output.

```2017-04-03 10:45:50,283 INFO  [c.u.s.s.i.SlackWebSocketSessionImpl] connecting to slack
2017-04-03 10:45:51,528 INFO  [c.u.s.s.i.SlackWebSocketSessionImpl] Team T0BA3ULKT : CCPL
2017-04-03 10:45:51,529 INFO  [c.u.s.s.i.SlackWebSocketSessionImpl] Self U4U2W1F5M : pinbot
2017-04-03 10:45:51,529 INFO  [c.u.s.s.i.SlackWebSocketSessionImpl] 18 users found on this session
2017-04-03 10:45:51,529 INFO  [c.u.s.s.i.SlackWebSocketSessionImpl] 20 channels found on this session
2017-04-03 10:45:52,932 WARN  [o.g.g.f.DefaultFilterChain] Exception during FilterChain execution
java.lang.NoSuchMethodError: org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket$4.obtainSslConnectionContext(Lorg/glassfish/grizzly/Connection;)Lorg/glassfish/grizzly/ssl/SSLConnectionContext;
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket$4.access$300(GrizzlyClientSocket.java:652) ~[tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket$4$1.onComplete(GrizzlyClientSocket.java:662) ~[tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.grizzly.ssl.SSLBaseFilter.notifyHandshakeComplete(SSLBaseFilter.java:880) ~[grizzly-framework-2.3.8.jar:2.3.8]
	at org.glassfish.grizzly.ssl.SSLFilter.notifyHandshakeComplete(SSLFilter.java:282) ~[grizzly-framework-2.3.8.jar:2.3.8]
	at org.glassfish.grizzly.ssl.SSLBaseFilter.handleRead(SSLBaseFilter.java:275) ~[grizzly-framework-2.3.8.jar:2.3.8]
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119) ~[grizzly-framework-2.3.8.jar:2.3.8]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:288) [grizzly-framework-2.3.8.jar:2.3.8]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:206) [grizzly-framework-2.3.8.jar:2.3.8]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:136) [grizzly-framework-2.3.8.jar:2.3.8]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:114) [grizzly-framework-2.3.8.jar:2.3.8]
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77) [grizzly-framework-2.3.8.jar:2.3.8]
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:547) [grizzly-framework-2.3.8.jar:2.3.8]
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:113) [grizzly-framework-2.3.8.jar:2.3.8]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:115) [grizzly-framework-2.3.8.jar:2.3.8]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:55) [grizzly-framework-2.3.8.jar:2.3.8]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:135) [grizzly-framework-2.3.8.jar:2.3.8]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565) [grizzly-framework-2.3.8.jar:2.3.8]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545) [grizzly-framework-2.3.8.jar:2.3.8]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
2017-04-03 10:46:22,736 ERROR [c.u.s.s.i.SlackWebSocketSessionImpl] javax.websocket.DeploymentException: Connection to 'wss://mpmulti-spwu.slack-msgs.com/websocket/<elided>' failed.
```

**Comment by Manasaanand** [comment]
Have you got any solution for this?

**Comment by bcorne** [comment]
I would bet on a classpath order issue. Looking at your stacktrace (which gives the jar files used) it seems that grizzly-framework-2.3.8.jar is loaded before tyrus-standalone-client-1.13.jar. The tyrus jar contains already its own version of the grizzly framework (a more recent one than the 2.3.8). The only solution I could provide would be maybe to get rid of your grizzly-framework jar if you can or change the classpath order to ensure tyrus jar is loaded before grizzly framework. Are you running the bot from a web application ?

**Comment by bittiez** [comment]
Try connecting with this method: `SlackSessionFactory.getSlackSessionBuilder("my-bot-auth-token").withAutoreconnectOnDisconnection(true).withConnectionHeartbeat(10, TimeUnit.SECONDS).build()`

This may not be the solution to your issue but it may help you further down the road staying connected

**Comment by david-hosier** [comment]
Sorry, I didn't realize that this had responses. The problem was definitely with the grizzly stuff. I recently refactored my small app to use Spring Boot, and the problems have gone away, and I'm no happily using a bot in my Slack space using the API.
