### ISSUE TITLE
NPE caught by onError in 1.0.0

### ISSUE THREAD

**Issue by rdifalco** [Ullink/simple-slack-api#182]
I'm getting intermittent NPE exceptions here, which I wouldn't expect. 

```
SlackWebSocketSessionImpl:

    public void onMessage(String message) {
        final JsonObject object = parseObject(message);

        LOGGER.debug("receiving from websocket " + message);
-->     if ("pong".equals(object.get("type").getAsString())) {
            lastPingAck = object.get("reply_to").getAsInt();
            LOGGER.debug("pong received " + lastPingAck);
        }
```
Here's the stack trace:
```
java.lang.NullPointerException: null
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.onMessage(SlackWebSocketSessionImpl.java:944) 
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.onMessage(SlackWebSocketSessionImpl.java:54) 
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:562) 
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:812) 
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:200) 
	at org.glassfish.tyrus.core.frame.TextFrame.respond(TextFrame.java:135) 
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:635) 
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:664) 
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:472) 
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:114) 
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91) 
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:270) 
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119) 
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284) 
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201) 
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133) 
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112) 
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77) 
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561) 
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112) 
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117) 
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56) 
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137) 
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565) 
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545) 
	at java.lang.Thread.run(Unknown Source) 
```

**Comment by kahliloppenheimer** [comment]
I've been seeing this recently as well. Is there a known fix to this issue?

**Comment by bcorne** [comment]
This is due to a message received without a 'type' attribute. The lib can't parse it. I've pushed a commit checking the presence of this attribute and logging the flawed message if the type is missing.

**Comment by kahliloppenheimer** [comment]
Sweet, thanks so much!
