### ISSUE TITLE
org.glassfish.tyrus.bundles:tyrus-standalone-client dependency should not be optional

### ISSUE THREAD

**Issue by Gilead** [Ullink/simple-slack-api#197]
Out of the box SimpleSlackAPI doesn't work and throws an exception unless one adds the dependency manually to the pom:

```
		<dependency>
			<groupId>org.glassfish.tyrus.bundles</groupId>
			<artifactId>tyrus-standalone-client</artifactId>
			<version>1.13.1</version>
		</dependency>
```

The exception is as follows:
```
java.lang.NoClassDefFoundError: org/glassfish/tyrus/client/ClientManager
	at com.ullink.slack.simpleslackapi.impl.DefaultWebSocketContainerProvider.getWebSocketContainer(DefaultWebSocketContainerProvider.java:33)
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.establishWebsocketConnection(SlackWebSocketSessionImpl.java:338)
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connectImpl(SlackWebSocketSessionImpl.java:331)
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connect(SlackWebSocketSessionImpl.java:285)
....
```

**Comment by MRylander** [comment]
It looks like there is a fix for this in master (https://github.com/Ullink/simple-slack-api/commit/bf3cc89ec6ab14fd35aae8ff41305be218afd3d0) but a patch release is need. Can we get a v1.0.1 with this fix in?

**Comment by bcorne** [comment]
next release will be provided soon

**Comment by dustinjohnson13** [comment]
Also waiting for this.... thanks!
