### ISSUE TITLE
Sporadic null pointer when first connecting

### ISSUE THREAD

**Issue by collinscangarella** [Ullink/simple-slack-api#210]
Version: 1.0.0

This happens sometimes when connecting to slack for the first time. Here's the code that is called:

```
SlackSession session = SlackSessionFactory.createWebSocketSlackSession(token);
session.connect();
```

And the logger output: 

```
14:09:32.800 [main] INFO  c.u.s.s.i.SlackWebSocketSessionImpl - slack session ready
14:09:32.800 [main] DEBUG c.u.s.s.i.SlackWebSocketSessionImpl - starting actions monitoring
14:09:32.800 [Thread-10] DEBUG c.u.s.s.i.SlackWebSocketSessionImpl - monitoring thread started
14:09:56.333 [Thread-1] WARN  c.u.s.s.i.SlackWebSocketSessionImpl - Connection lost...
14:09:56.334 [Thread-1] DEBUG c.u.s.s.i.SlackWebSocketSessionImpl - initiating actions to websocket
14:09:56.492 [Thread-1] DEBUG c.u.s.s.i.SlackWebSocketSessionImpl - websocket actions established
14:09:56.493 [Thread-1] INFO  c.u.s.s.i.SlackWebSocketSessionImpl - slack session ready
14:09:56.639 [Grizzly(2)] DEBUG c.u.s.s.i.SlackWebSocketSessionImpl - receiving from websocket {"type":"error","error":{"msg":"Socket URL has expired","code":1}}
14:09:56.639 [Grizzly(2)] WARN  c.u.s.s.i.SlackWebSocketSessionImpl - event of type UNKNOWN not handled: com.ullink.slack.simpleslackapi.events.SlackEvent$1@f4b7669
14:09:56.639 [Grizzly(2)] DEBUG c.u.s.s.i.SlackWebSocketSessionImpl - receiving from websocket {}
14:09:56.639 [Grizzly(2)] ERROR c.u.s.s.i.SlackWebSocketSessionImpl - Endpoint#onError called
java.lang.NullPointerException: null
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.onMessage(SlackWebSocketSessionImpl.java:944) ~[simpleslackapi-1.0.0.jar:na]
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.onMessage(SlackWebSocketSessionImpl.java:54) ~[simpleslackapi-1.0.0.jar:na]
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:576) ~[tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:879) ~[tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:216) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.tyrus.core.frame.TextFrame.respond(TextFrame.java:139) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:807) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:747) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:476) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:114) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:272) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591) [tyrus-standalone-client-1.13.jar:na]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571) [tyrus-standalone-client-1.13.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

**Comment by kahliloppenheimer** [comment]
Seems like the same issue mentioned in #182. Is there a known fix for this? My logs are filled with these NPEs currently.

**Comment by kahliloppenheimer** [comment]
cc @bcorne

**Comment by bcorne** [comment]
thanks again for the fix
