### ISSUE TITLE
NoClassDefFoundError in Android Build

### ISSUE THREAD

**Issue by sirvon** [Ullink/simple-slack-api#24]
```java
Stacktrace
----------------
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/HttpClientBuilder;
    at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.getHttpClient(SlackWebSocketSessionImpl.java:373)
    at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connect(SlackWebSocketSessionImpl.java:148)
    at com.loqooapps.Views.Activities.Startup.onCreate(Startup.java:322)
    at android.app.Activity.performCreate(Activity.java:6056)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2441)
    at android.app.ActivityThread.access$800(ActivityThread.java:162)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5431)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.client.HttpClientBuilder" on path: DexPathList[[zip file "/data/app/com.teamxna.fmc.inhouse-2/base.apk"],nativeLibraryDirectories=[/data/app/com.teamxna.fmc.inhouse-2/lib/arm, /vendor/lib, /system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
    ... 16 more
    Suppressed: java.lang.ClassNotFoundException: org.apache.http.impl.client.HttpClientBuilder
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoade…
```

**Comment by bcorne** [comment]
Hi,

The library has some dependencies you need to package with your application : 

org.glassfish.tyrus.bundles:tyrus-standalone-client:1.8.3
com.googlecode.json-simple:json-simple:1.1.1
org.slf4j:slf4j-api:1.7.7
org.apache.httpcomponents:httpclient:4.4 (looks like this one is missing according to your stacktrace)
com.google.guava:guava:18.0

Best regards,

Benoit
