### ISSUE TITLE
got exception when answering to thread

### ISSUE THREAD

**Issue by oshai** [Ullink/simple-slack-api#266]
This is my code (in kotlin):
```
val session = SlackSessionFactory.createWebSocketSlackSession("bot token")
    session.connect()
    val channel = session.findChannelByName("test") //make sure bot is a member of the channel.
    val mr = session.sendMessage(channel, "hi im a bot")
    session.sendMessage(channel, SlackPreparedMessage.Builder()
        .withMessage("I also reply")
        .withThreadTimestamp(mr.reply.timestamp)
        .build())
```

And this is the exception:
```
10:04:07.698 [Grizzly(1)] ERROR com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - Endpoint#onError called
java.lang.ClassCastException: com.ullink.slack.simpleslackapi.events.SlackEvent$1 cannot be cast to com.ullink.slack.simpleslackapi.events.UnknownEvent
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl$EventDispatcher.dispatch(SlackWebSocketSessionImpl.java:239) ~[simpleslackapi-1.2.0.jar:?]
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.onMessage(SlackWebSocketSessionImpl.java:1074) ~[simpleslackapi-1.2.0.jar:?]
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.onMessage(SlackWebSocketSessionImpl.java:57) ~[simpleslackapi-1.2.0.jar:?]
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:576) ~[tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:879) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:216) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.tyrus.core.frame.TextFrame.respond(TextFrame.java:139) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:807) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:747) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:476) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:114) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:272) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591) [tyrus-standalone-client-1.13.1.jar:?]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571) [tyrus-standalone-client-1.13.1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
```

**Comment by oshai** [comment]
@bcorne maybe you can help? I see in the code there are both `SlackEvent.UNKNOWN_EVENT` and `UnknownEvent` which are not of the same type.

**Comment by oshai** [comment]
I see this is already fixed on master. Is it released already?

**Comment by sergey-morenets** [comment]
@oshai It seems this library is dead
