### ISSUE TITLE
Error session.connect()

### ISSUE THREAD

**Issue by fatihcalis** [Ullink/simple-slack-api#56]
[main] INFO com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - connecting to slack
Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:52)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:56)
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:46)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:72)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:84)
	at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<clinit>(ManagedHttpClientConnectionFactory.java:59)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingHttpClientConnectionManager.java:493)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:149)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:138)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:114)
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:726)
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.getHttpClient(SlackWebSocketSessionImpl.java:671)
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connectImpl(SlackWebSocketSessionImpl.java:254)
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connect(SlackWebSocketSessionImpl.java:230)

I couldn't fix this

**Comment by bcorne** [comment]
Hi,

Which version of apache httpclient are you using?

Best regards,

Benoit

**Comment by fatihcalis** [comment]
httpclient-4.3.4

**Comment by bcorne** [comment]
Ok, so the issue you have. This library needs the following libraries : 

- org.glassfish.tyrus.bundles:tyrus-standalone-client:1.8.3
- com.googlecode.json-simple:json-simple:1.1.1
- org.slf4j:slf4j-api:1.7.7
- org.apache.httpcomponents:httpclient:4.4
- com.google.guava:guava:18.0
- ch.qos.logback:logback-classic:1.1.3
- org.threeten:threetenbp:1.3.1


Best regards,

Benoit

**Comment by fatihcalis** [comment]
`15:05:37.601 [main] INFO  c.u.s.s.i.SlackWebSocketSessionImpl - connecting to slack
Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:912)
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.getHttpClient(SlackWebSocketSessionImpl.java:671)
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connectImpl(SlackWebSocketSessionImpl.java:254)
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connect(SlackWebSocketSessionImpl.java:230)`

now ı am facing this problem. What am I doing wrong ?

**Comment by bcorne** [comment]
Well, it seems that's the same issue, did you move to apache httpclient 4.4 ? if so you might have a classpath issue (multiple version of httpclient in your classpath and the wrong one is loaded)

**Comment by fatihcalis** [comment]
I realize that there is another version of httpclient in my classpath beceuse of ı use google analytics api at the same time. Finally , my problem is solved. 

Thank you !!!

**Comment by bcorne** [comment]
You're welcome, have fun with this lib :)
