### ISSUE TITLE
Keep-alive mechanism fails when connection is closed (probably due to network error)

### ISSUE THREAD

**Issue by nilsga** [Ullink/simple-slack-api#6]
In some cases, I get this error. After this occurs, the session no longer responds to messages sent.

```
[WARNING]
java.lang.IllegalStateException: The connection has been closed.
        at org.glassfish.tyrus.core.TyrusSession.checkConnectionState(TyrusSession.java:518)
        at org.glassfish.tyrus.core.TyrusSession.getBasicRemote(TyrusSession.java:206)
        at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl$2.run(SlackWebSocketSessionImpl.java:189)
```

It seems that this case is not handled by the `connectionMonitoringThread`, and the error causes the session to become invalid.

**Comment by bcorne** [comment]
Hi, 

Yes the current connection monitoring mechanism needs to be revamped, I'll add that to my todo list :)

**Comment by bcorne** [comment]
I made some changes which should improve the Keep Alive mechanism
