### ISSUE TITLE
Exception in thread "main" java.net.UnknownHostException: slack.com

### ISSUE THREAD

**Issue by NarendraDRR** [Ullink/simple-slack-api#62]
Hi,
I am getting the below error while executing the "SlackDirectConnection.java"
Exception in thread "main" java.net.UnknownHostException: slack.com
at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
I am unable to find from your are passing "slack.com"
Please let us know how to resolve this.
Thanks in Advance.

**Comment by bcorne** [comment]
Hi, 

According to the stacktrace, it looks like the user you're passing  to sendMessageToUser is null.

Could you check that part?

Best regards,

Benoit

**Comment by NarendraDRR** [comment]
Hi Benoit,

Thanks a lot your support. Now we are able to send message to the direct user or specific channel.
But end of the session/execution we are getting the following exception:
"[main] ERROR com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl - javax.websocket.DeploymentException: Handshake response not received."
Could please suggest how to avoid this exception.

And we have to send message with attachment to the user/channel
we have tried to pass attachment/file path in the following way, but the image/attachment is not delivered to user. Only message is delivering to user.
       SlackAttachment attachment =new SlackAttachment();
       attachment.thumb_url="/Users/Desktop/SlackJars.png"; 
       SendingMessages s =new SendingMessages(); 
       s.sendDirectMessageToAUser(session,"jay","Hi, How are you?",attachment);
Please let us know how to pass image url.
Thanks in Advance.
